apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: echoserver
  namespace: echoserver
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- httproute.yaml
- httproute-ip.yaml
- db-secret.enc.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: homelab
patchesStrategicMerge: []